/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathgame_v1;

import javax.swing.JOptionPane;

/**
 *
 * @author rahul
 */
public class HighPlay extends javax.swing.JFrame {

    
    int actualAnswer,a,b,Answer,right,wrong;
    static int choice;
    long startTime,endTime,totalTime;
  String summary="";
    public HighPlay() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HighPlayBtn = new javax.swing.JButton();
        HighBackBtn = new javax.swing.JButton();
        AnsField = new javax.swing.JTextField();
        QuesField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HighPlayBtn.setBackground(new java.awt.Color(51, 51, 51));
        HighPlayBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        HighPlayBtn.setText("Play");
        HighPlayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighPlayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HighPlayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 90, 30));

        HighBackBtn.setBackground(new java.awt.Color(51, 51, 51));
        HighBackBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        HighBackBtn.setText("Back");
        HighBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighBackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HighBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 30));

        AnsField.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        getContentPane().add(AnsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 120, 40));

        QuesField.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        QuesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuesFieldActionPerformed(evt);
            }
        });
        getContentPane().add(QuesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel1.setText("What Is");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel2.setText("Answer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel3.setText("??");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, 40));

        SubmitBtn.setBackground(new java.awt.Color(51, 51, 51));
        SubmitBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, 30));

        NextBtn.setBackground(new java.awt.Color(51, 51, 51));
        NextBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        NextBtn.setText("Question");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(NextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 250, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 0));
        jLabel4.setText("H");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 20));

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 60, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgame_v1/profile.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 410, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HighBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighBackBtnActionPerformed
          int c=JOptionPane.showConfirmDialog(null,"Are You Sure","Warning",JOptionPane.YES_NO_OPTION);
          if(c==JOptionPane.YES_OPTION){
             MathStart M=new MathStart();
             String s=jLabel5.getText();
             M.jLabel1.setText(s);
             M.setVisible(true);
             dispose();
         }
         else{
             return;
         }
    }//GEN-LAST:event_HighBackBtnActionPerformed

    private void HighPlayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighPlayBtnActionPerformed
        startTime=System.currentTimeMillis();
        HighPlayBtn.setVisible(false);
        choice=Integer.parseInt(JOptionPane.showInputDialog(null,"How Many Question Do You Want"));
    }//GEN-LAST:event_HighPlayBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        Summery h=new Summery();
       Answer=Integer.parseInt(AnsField.getText());
       summary = summary+"\n" +a+ " + " +b+ " = " +Answer+ " it was " +(Answer == actualAnswer);   
       if(Answer==actualAnswer){
           JOptionPane.showMessageDialog(null,"Correct");
           right++;
       }
       else if(Answer != actualAnswer){
           JOptionPane.showMessageDialog(null,"Wrong");
           wrong++;
       }
       if(choice== right+wrong){
            NextBtn.setVisible(false);
            QuesField.setText("");
            AnsField.setText("");
            SubmitBtn.setVisible(false);
            //jButton1.setVisible(true);
            dispose();
            h.setVisible(true);
            endTime = System.currentTimeMillis();
            totalTime = endTime - startTime;
            String s=jLabel5.getText();
            h.jLabel1.setText(s);
            h.jTextField1.setText(""+right+"");
            h.jTextField2.setText(""+totalTime/1000+ " s");
            h.jTextArea1.append("Summary \n"+summary);
}
    
      
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
           AnsField.setText("");
           a=(int)(Math.random()*30);
           b=(int)(Math.random()*30);
           
        if(a==0||b==0){
            a+=2;
            b+=2;
        }  
             QuesField.setText(" "+a+"+"+b);
             actualAnswer=a+b;
             
       
        
    }//GEN-LAST:event_NextBtnActionPerformed

    private void QuesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuesFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnsField;
    private javax.swing.JButton HighBackBtn;
    private javax.swing.JButton HighPlayBtn;
    private javax.swing.JButton NextBtn;
    private javax.swing.JTextField QuesField;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
