
package mathgame_v1;

import javax.swing.JOptionPane;

/**
 *
 * @author rahul
 */
public class LowPlay extends javax.swing.JFrame {

  int actualAnswer,a,b,Answer,right,wrong;
  static int choice;
  long startTime,endTime,totalTime;
  String summary="";
    public LowPlay() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LowPlayBtn = new javax.swing.JButton();
        LowBackBtn = new javax.swing.JButton();
        LowAnsField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LowQuesField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LowSubmitBtn = new javax.swing.JButton();
        LowNextBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LowPlayBtn.setBackground(new java.awt.Color(51, 51, 51));
        LowPlayBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        LowPlayBtn.setText("Play");
        LowPlayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowPlayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LowPlayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 90, 30));

        LowBackBtn.setBackground(new java.awt.Color(51, 51, 51));
        LowBackBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        LowBackBtn.setText("Back");
        LowBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowBackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LowBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 30));

        LowAnsField.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        getContentPane().add(LowAnsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel1.setText("What Is");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel2.setText("??");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        LowQuesField.setEditable(false);
        LowQuesField.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        LowQuesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowQuesFieldActionPerformed(evt);
            }
        });
        getContentPane().add(LowQuesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 120, 40));

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel3.setText("Answer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 40));

        LowSubmitBtn.setBackground(new java.awt.Color(51, 51, 51));
        LowSubmitBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        LowSubmitBtn.setText("Submit");
        LowSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowSubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LowSubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, 30));

        LowNextBtn.setBackground(new java.awt.Color(51, 51, 51));
        LowNextBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        LowNextBtn.setText("Question");
        LowNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowNextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LowNextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel4.setText("E");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 70, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgame_v1/profile.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 410, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LowBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowBackBtnActionPerformed
         
  
             MathStart M=new MathStart();
             String s=jLabel5.getText();
             M.jLabel1.setText(s);
             M.setVisible(true);
             dispose();
         
       
    }//GEN-LAST:event_LowBackBtnActionPerformed

    private void LowQuesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowQuesFieldActionPerformed
        
    }//GEN-LAST:event_LowQuesFieldActionPerformed

    private void LowPlayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowPlayBtnActionPerformed
        startTime=System.currentTimeMillis();
        LowPlayBtn.setVisible(false);
        choice=Integer.parseInt(JOptionPane.showInputDialog("How Many Question Do You Want"));
    }//GEN-LAST:event_LowPlayBtnActionPerformed

    private void LowSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowSubmitBtnActionPerformed
       Summery h=new Summery();
       Answer=Integer.parseInt(LowAnsField.getText());
       summary = summary+"\n" +a+ " + " +b+ " = " +Answer+ " it was " +(Answer == actualAnswer);   
       if(Answer==actualAnswer){
           JOptionPane.showMessageDialog(null,"Correct");
           right++;
       }
       else if(Answer != actualAnswer){
           JOptionPane.showMessageDialog(null,"Wrong");
           wrong++;
       }
       if(choice== right+wrong){
            LowNextBtn.setVisible(false);
            LowQuesField.setText("");
            LowAnsField.setText("");
            LowSubmitBtn.setVisible(false);
            //jButton1.setVisible(true);
            dispose();
            h.setVisible(true);
            endTime = System.currentTimeMillis();
            totalTime = endTime - startTime;
            String s=jLabel5.getText();
            h.jLabel1.setText(s);
            h.jTextField1.setText(""+right);
            h.jTextField3.setText(""+wrong);
            h.jTextField2.setText(""+totalTime/1000);
            h.jTextArea1.append("Summary \n"+summary);
}
    
      
       
    }//GEN-LAST:event_LowSubmitBtnActionPerformed

    private void LowNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowNextBtnActionPerformed
           LowAnsField.setText("");
           a=(int)(Math.random()*10);
           b=(int)(Math.random()*10);
           
        if(a==0||b==0){
            a+=2;
            b+=2;
        }  
             LowQuesField.setText(" "+a+"+"+b);
             actualAnswer=a+b;
             
            
    }//GEN-LAST:event_LowNextBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LowPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LowPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LowPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LowPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LowPlay().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LowAnsField;
    private javax.swing.JButton LowBackBtn;
    public javax.swing.JButton LowNextBtn;
    private javax.swing.JButton LowPlayBtn;
    private javax.swing.JTextField LowQuesField;
    private javax.swing.JButton LowSubmitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
