/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathgame_v1;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
public class MathStart extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public MathStart() {
        initComponents();
        conn=SQlite.ConnecrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LowBtn = new javax.swing.JButton();
        MediumBtn = new javax.swing.JButton();
        HighBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LowBtn.setBackground(new java.awt.Color(51, 51, 51));
        LowBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        LowBtn.setText("Easy");
        LowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, 30));

        MediumBtn.setBackground(new java.awt.Color(51, 51, 51));
        MediumBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        MediumBtn.setText("Medium");
        MediumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumBtnActionPerformed(evt);
            }
        });
        getContentPane().add(MediumBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 30));

        HighBtn.setBackground(new java.awt.Color(51, 51, 51));
        HighBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        HighBtn.setText("Hard");
        HighBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HighBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, 30));

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("LEVEL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 3, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgame_v1/profile.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowBtnActionPerformed
        LowPlay L=new LowPlay();
        L.setVisible(true);
        String s=jLabel1.getText();
        L.jLabel5.setText(s);
        //L.jButton1.setVisible(false);
        dispose();
       
        
    }//GEN-LAST:event_LowBtnActionPerformed

    private void MediumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumBtnActionPerformed
        MediumPlay M=new MediumPlay();
        String s=jLabel1.getText();
        M.jLabel5.setText(s);
        M.setVisible(true);
        dispose();
    }//GEN-LAST:event_MediumBtnActionPerformed

    private void HighBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighBtnActionPerformed
        HighPlay M=new HighPlay();
        String s=jLabel1.getText();
        M.jLabel5.setText(s);
        M.setVisible(true);
        dispose();
    }//GEN-LAST:event_HighBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
       Add_Sub_Mul_Div_Ran M=new Add_Sub_Mul_Div_Ran();
       String s=jLabel1.getText();
       M.jLabel2.setText(s);
       M.setVisible(true);
       dispose();

    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton HighBtn;
    private javax.swing.JButton LowBtn;
    private javax.swing.JButton MediumBtn;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
