
package mathgame_v1;

import javax.swing.JOptionPane;

import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class MathPlay extends javax.swing.JFrame {
    Profile p=new Profile();
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public MathPlay() {
        initComponents();
        conn=SQlite.ConnecrDB();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        QuickplayBtn = new javax.swing.JButton();
        PlayonlineBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        QuickplayBtn.setBackground(new java.awt.Color(51, 51, 51));
        QuickplayBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        QuickplayBtn.setText("Quick Play");
        QuickplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickplayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(QuickplayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, 30));

        PlayonlineBtn.setBackground(new java.awt.Color(51, 51, 51));
        PlayonlineBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        PlayonlineBtn.setText("Random");
        PlayonlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayonlineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PlayonlineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, 30));

        ExitBtn.setBackground(new java.awt.Color(51, 51, 51));
        ExitBtn.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 3, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 70, 30));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jButton3.setText("Profile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel1.setText("Option");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 30, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgame_v1/profile.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void QuickplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickplayBtnActionPerformed
         Add_Sub_Mul_Div_Ran asmd=new Add_Sub_Mul_Div_Ran();
         String t=jLabel3.getText();
         asmd.jLabel2.setText(t);
         //MathStart M=new MathStart();
         asmd.setVisible(true);
         dispose();
         
    }//GEN-LAST:event_QuickplayBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
         int choice=JOptionPane.showConfirmDialog(null,"Are You Sure ?","Attention",JOptionPane.YES_NO_OPTION);
         if(choice==JOptionPane.YES_OPTION){
             System.exit(0);
         }
         
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void PlayonlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayonlineBtnActionPerformed
         PlayOnline P=new  PlayOnline();
         P.setVisible(true);
         
         dispose();
    }//GEN-LAST:event_PlayonlineBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       SQl l=new SQl();
       l.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Profile p=new Profile();
       p.setVisible(true);
       //p.jTable1.setVisible(false);
      dispose();
       try{
       String q="Select * from Last";
       pst=conn.prepareStatement(q);
       rs=pst.executeQuery();
      
       p.jTable1.setModel(DbUtils.resultSetToTableModel(rs));
       String t=jLabel3.getText();
        p.NameField.setText(t);
       //JOptionPane.showMessageDialog(null,"Success");
       }
       catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
       }
       
      
      
      
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton PlayonlineBtn;
    private javax.swing.JButton QuickplayBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
