/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathgame_v1;

import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class Profile extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public Profile() {
        initComponents();
        
        
    }
public int getSum(){
        
        int rowCount=jTable1.getRowCount();
        int sum=0;
        for(int i=0;i<rowCount;i++){
            sum=sum+Integer.parseInt(jTable1.getValueAt(i,0).toString());
        }
        
        return sum;   
}
public int getWrong(){
        
        int rowCount=jTable1.getRowCount();
        int Wrong=0;
        for(int i=0;i<rowCount;i++){
            Wrong=Wrong+Integer.parseInt(jTable1.getValueAt(i,2).toString());
        }
        
        return Wrong;   
}
public int getTime(){
        
        int rowCount=jTable1.getRowCount();
        int Time=0;
        for(int i=0;i<rowCount;i++){
            Time=Time+Integer.parseInt(jTable1.getValueAt(i,1).toString());
        }
        
        return Time;   
}
public int getPlay(){
        
        int rowCount=jTable1.getRowCount();
        int Play=0;
        for(int i=0;i<rowCount;i++){
            Play=Play+Integer.parseInt(jTable1.getValueAt(i,4).toString());
        }
        
        return Play;  

}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        NameField = new javax.swing.JTextField();
        CorectField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PressBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TtlPlayField = new javax.swing.JTextField();
        TotalTimeField = new javax.swing.JTextField();
        WrongField = new javax.swing.JTextField();
        GamePlayField = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameField.setEditable(false);
        NameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 100, 30));

        CorectField.setEditable(false);
        CorectField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(CorectField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 100, 30));

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 40, 10));

        PressBtn.setText("Press");
        PressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PressBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PressBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arno Pro", 1, 24)); // NOI18N
        jLabel1.setText("Total Question");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 30));

        jLabel2.setFont(new java.awt.Font("Arno Pro SmText", 1, 24)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel3.setFont(new java.awt.Font("Arno Pro", 1, 24)); // NOI18N
        jLabel3.setText("Wrong");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 30));

        jLabel4.setFont(new java.awt.Font("Arno Pro", 1, 24)); // NOI18N
        jLabel4.setText("Correct");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        jLabel5.setFont(new java.awt.Font("Arno Pro", 1, 24)); // NOI18N
        jLabel5.setText("Total Time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 30));

        jLabel6.setFont(new java.awt.Font("Arno Pro", 1, 24)); // NOI18N
        jLabel6.setText("Game Play");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));

        TtlPlayField.setEditable(false);
        TtlPlayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TtlPlayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 100, 30));

        TotalTimeField.setEditable(false);
        TotalTimeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TotalTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 100, 30));

        WrongField.setEditable(false);
        WrongField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(WrongField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 100, 30));

        GamePlayField.setEditable(false);
        GamePlayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(GamePlayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 100, 30));

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgame_v1/profile.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PressBtnActionPerformed
       try{
           int i=0;
           CorectField.setText(Integer.toString(getSum()));
           WrongField.setText(Integer.toString(getWrong()));
           TotalTimeField.setText(Integer.toString(getTime())+" s");
           GamePlayField.setText(Integer.toString(getPlay()));
           int a=Integer.parseInt(CorectField.getText());
           int b=Integer.parseInt(WrongField.getText());
           int c=a+b;
           TtlPlayField.setText(Integer.toString(c));
           NameField.setText("Rahul");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       
    }//GEN-LAST:event_PressBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        MathPlay m=new MathPlay();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField CorectField;
    private javax.swing.JTextField GamePlayField;
    public javax.swing.JTextField NameField;
    private javax.swing.JButton PressBtn;
    private javax.swing.JTextField TotalTimeField;
    private javax.swing.JTextField TtlPlayField;
    private javax.swing.JTextField WrongField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
